version: "3.9"

services:
    proxy:
        image: docker/proxy
        build: ./proxy
        container_name: proxy
        ports:
           - 80:80
        depends_on: 
           - deliverycx_client_desktop
           - deliverycx_client   
        networks:
          - mynetwork
    deliverycx_client_desktop:
        image: docker/client_desktop
        container_name: development_client_desktop
        build:
            context: ./client_desktop
        ports:
          - "3000:3000"
        networks:
          - mynetwork
    deliverycx_client:
        image: docker/client
        container_name: development_client
        build: ./client
        ports:
          - "88:88"
        
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
        networks:
          - mynetwork

networks:
  mynetwork:
    external:
      name: delivglobalnetwork 