export const DELIVERY_METODS = {
	COURIER:"COURIER",
  PICKUP:"PICKUP",
	ONSPOT:"ONSPOT"
}
export const ORG_STATUS = {
	HIDDEN:"HIDDEN",
	WORK:"WORK",
	NODELIVERY:"NODELIVERY",
	NOWORK:"NOWORK",
	OPEN:"OPEN"
}
export const PAYMENT_METODS = {
	CASH:"CASH",
	BYCARD:"BYCARD",
	CARD:"PAY"
}

export const DILIVERY_TIME_STATUS = {
	NODELIVERY:"NODELIVERY",
	ONLIPICKUP:"ONLIPICKUP"
}